batch_policy: "continuousbatch"
priority: "decode"
max_running_requests: 24
max_overload_requests: 0
chunked_prefill: True
max_batch_fill_tokens: 2048
max_batch_embed_images: 8
batch_embed_prefill: False
debug: False