defaults:
  - cluster: auto
  - _self_

model:
  path: null
  dtype: "auto"
  device: "auto"  

zmq:
  host: "auto"
  port: -1

apiserver:
  host: "127.0.0.1"
  port: 8888
  zmq: ${zmq}
  model: ${model}
  tpot_slo: ${tpot_slo}

cluster: 
  ebalancer:
    policy: "round"
  pbalancer:
    policy: "round"
  ray_cluster_port: -1
  debug: false
  log_server_path: "hydrainfer_log_server.json"

intranode_migrate_backend: "auto"
internode_migrate_backend: "nccl"
debug_migrate: false
ignore_eos: False

hydra:  
  output_subdir: null  
  run:  
    dir: "hydra_log"

ttft_slo: 2
tpot_slo: 0.4

log_latency_breakdown: false
enable_prefix_cache: false