defaults:
  - cluster: hybrid
  - _self_

model:
  path: null
  dtype: "auto"
  device: "auto"  

mode: "online"

zmq:
  host: "auto"
  port: -1

apiserver:
  host: "127.0.0.1"
  port: 8888
  zmq: ${zmq}
  model: ${model}
  chat_template: null

nccl_communicator:
  host: "auto"
  port: -1

cluster: 
  ebalancer:
    policy: "round"
  pbalancer:
    policy: "round"
  ray_cluster_port: -1
  debug: false

intranode_migrate_backend: "ipc"
internode_migrate_backend: "nccl"
log_latency_breakdown: false
ignore_eos: False

hydra:  
  output_subdir: null  
  run:  
    dir: "hydra_log"