defaults:
  - cluster: auto
  - _self_

model:
  path: null
  dtype: "auto"
  device: "auto"  

zmq:
  host: "auto"
  port: -1

apiserver:
  host: "127.0.0.1"
  port: 8888
  zmq: ${zmq}
  model: ${model}

cluster: 
  ebalancer:
    policy: "round"
  pbalancer:
    policy: "round"
  ray_cluster_port: -1
  debug: false

intranode_migrate_backend: "auto"
internode_migrate_backend: "nccl"
debug_migrate: false
log_latency_breakdown: false
ignore_eos: False

hydra:  
  output_subdir: null  
  run:  
    dir: "hydra_log"