name: "llava-hf/llava-1.5-7b-hf"
path: null
dtype: "fp16"
device: "cuda"

vision:
    image_token_id: 32000
    num_image_tokens: 576

language:
    n_layers: 32
    max_position_embeddings: 4096
    n_qo_heads: 32
    n_kv_heads: 32
    head_dim: 128