defaults:
  - ../engine/request_processor@request_processor
  - ../engine/batch_scheduler@batch_scheduler
  - ../engine/executor@executor
  - ../engine/batch_scheduler_profiler@batch_scheduler_profiler
model: ${model}
zmq: ${zmq}
debug_migrate: False
migrate_backend_config:
  intranode_migrate_backend: ${intranode_migrate_backend}
  internode_migrate_backend: ${internode_migrate_backend}
  debug: ${debug_migrate}
log_latency_breakdown: ${log_latency_breakdown}