defaults:
  - model: llava7b
  - node@cluster.ednode
  - node@cluster.pdnode
  - node@cluster.dnode
  - _self_

mode: "online"

zmq:
  host: "127.0.0.1"
  port: 40832

apiserver:
  host: "127.0.0.1"
  port: 8888
  zmq: ${zmq}

cluster:
  ednode:
    enable_encode: True
    enable_prefill: False
    enable_decode: True
    request_processor:
      ep_migrate: True
      pd_migrate: True
    batch_scheduler_profiler:
      tpot_slo: 0.08
  pdnode:
    enable_encode: False
    enable_prefill: True
    enable_decode: True
    request_processor:
      ep_migrate: False
      pd_migrate: True
    batch_scheduler_profiler:
      tpot_slo: 0.08
  dnode:
    enable_encode: False
    enable_prefill: False
    enable_decode: True
    batch_scheduler_profiler:
      tpot_slo: 0.04
    worker:
      has_vision_model: False
      has_language_model: True
  n_ednode: 1
  n_pdnode: 1
  n_dnode: 1