defaults:
  - model: llava7b
  - cluster: hybrid
  - _self_

mode: "online"

zmq:
  host: "127.0.0.1"
  port: 40832

apiserver:
  host: "127.0.0.1"
  port: 8888
  zmq: ${zmq}

nccl_communicator:
  host: "127.0.0.1"
  port: 8889

cluster: 
  ebalancer:
    policy: "round"
  pbalancer:
    policy: "round"

intranode_migrate_backend: "ipc"
internode_migrate_backend: "nccl"
log_latency_breakdown: false