defaults:
  - model: llava7b
  - cluster: hybrid
  - _self_

mode: "online"

zmq:
  host: "127.0.0.1"
  port: 40832

apiserver:
  host: "127.0.0.1"
  port: 8888
  zmq: ${zmq}

cluster: 
  ebalancer:
    policy: "round"
  pbalancer:
    policy: "round"