defaults:
  - engine/request_processor@request_processor
  - engine/batch_scheduler@batch_scheduler
  - engine/kv_cache@kv_cache
  - engine/image_cache@image_cache
  - engine/executor@executor
  - engine/worker@worker
  - engine/batch_scheduler_profiler@batch_scheduler_profiler
model: ${model}
enable_encode: True
enable_prefill: True
enable_decode: True
zmq: ${zmq}
debug_migrate: False