defaults:
  - node

enable_encode: True
enable_prefill: False
enable_decode: False
request_processor:
  ep_migrate: True
  pd_migrate: True
batch_scheduler_profiler:
  tpot_slo: 0.08
  profile_image_budgets: True
  profile_token_budgets: False
  profile_interference_encode_decode: False
worker:
  has_vision_model: True
  has_language_model: False
