defaults:
  - node

enable_encode: True
enable_prefill: True
enable_decode: True
request_processor:
  ep_migrate: False
  pd_migrate: False
batch_scheduler_profiler:
  tpot_slo: 0.04
  profile_image_budgets: True
  profile_token_budgets: True
  profile_interference_encode_decode: True