defaults:
  - ../engine/request_processor@request_processor
  - ../engine/batch_scheduler@batch_scheduler
  - ../engine/kv_cache@kv_cache
  - ../engine/image_cache@image_cache
  - ../engine/executor@executor
  - ../engine/worker@worker
  - ../engine/batch_scheduler_profiler@batch_scheduler_profiler
model: ${model}
enable_encode: True
enable_prefill: True
enable_decode: True
zmq: ${zmq}
debug_migrate: False
nccl_communicator: ${nccl_communicator}
intranode_migrate_backend: ${intranode_migrate_backend}
internode_migrate_backend: ${internode_migrate_backend}
log_latency_breakdown: ${log_latency_breakdown}
auto_compute_cache_memory: true