defaults:
  - node

enable_encode: False
enable_prefill: True
enable_decode: True
request_processor:
  ep_migrate: True
  pd_migrate: False
batch_scheduler_profiler:
  tpot_slo: 0.08
  profile_image_budgets: False
  profile_token_budgets: True
  profile_interference_encode_decode: False
worker:
  has_vision_model: False
  has_language_model: True